version: '3'
services:
  agoklocrm:
    image: agiklo/crm
    ports:
     - 8081:8080
  dev-crmpostgres:
    image: postgres
    ports:
     - 5432:5432
    environment:
     - POSTGRES_PASSWORD=root
